#!/usr/bin/env bash

# Creates a release on Sentry with the short commit hash as the release name
# and uploads the source map as a part of that new release.
#
# See: https://docs.sentry.io/platforms/javascript/sourcemaps/#hosting--uploading
#
# At runtime, Sentry is configured with the same release name so that
# any errors popping up are associated with the right release and Sentry
# loads the right source maps.
#
# Source maps are generated by the TypeScript compiler. See tsconfig.app.json.

set -e

cd "$(dirname $0)"

if [[ -z "$SENTRY_AUTH_TOKEN" ]]; then
    echo "SENTRY_AUTH_TOKEN env var not set"
    exit 1
fi

SENTRY_PROJECT="pf-affiliates-api"
SENTRY_ORGANIZATION="sc-sector-labs-srl"
SENTRY_RELEASE="$(git rev-parse --short HEAD)"
SENTRY_DIST="default"
SENTRY_REVISION="$(git rev-parse HEAD)"
SENTRY_REPO="$(git remote get-url origin | cut -d ':' -f2 | cut -d '.' -f1)"

sentry_releases_cli="yarn sentry-cli releases --org $SENTRY_ORGANIZATION --project $SENTRY_PROJECT"

$sentry_releases_cli \
    files \
    "$SENTRY_RELEASE" \
    upload-sourcemaps \
    --dist "$SENTRY_DIST" \
    --no-rewrite \
    dist/

$sentry_releases_cli \
    set-commits \
    -c "$SENTRY_REPO@$SENTRY_REVISION" \
    "$SENTRY_RELEASE"

$sentry_releases_cli \
    finalize \
    "$SENTRY_RELEASE"
